---
language: node_js
node_js:
  - "10"

branches:
  only:
    - master

cache: npm

install:
  - npm ci
  - npm run lerna bootstrap

script:
  - npm run lerna run build
  - npm test
  - git config --global user.name "${GH_NAME}"
  - git config --global user.email "${GH_EMAIL}"
  - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
  - npm run docs:install && GIT_USER="${GH_NAME}" npm run docs:publish
